---
version: "3"

services:
  pebble:
    image: us-central1-docker.pkg.dev/krantz-dev-default/pebble/pebble:latest
    command: pebble -config /pebble-config.json -strict -dnsserver 10.30.50.3:8053
    ports:
      - "14000:14000"  # HTTPS ACME API
      - "15000:15000"  # HTTPS Management API
    volumes:
      - ./pebble-config.json:/pebble-config.json
    networks:
      acme:
        ipv4_address: 10.30.50.2

  challtestsrv:
    image: us-central1-docker.pkg.dev/krantz-dev-default/pebble/pebble-challtestsrv:latest
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 10.30.50.3
    ports:
      - "8055:8055"  # HTTP Management API
    networks:
      acme:
        ipv4_address: 10.30.50.3

networks:
  acme:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24
