---
name: Lint
on: push  # yamllint disable-line rule:truthy

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - run: cargo fmt --check --all
      - run: cargo clippy -- -D warnings

  yaml:
    name: YAML
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: pip install yamllint

      - run: yamllint -s -f github .
