---
name: PR
on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
